version: '3.8'
services:
  config-server:
    image: config-server
    container_name: config-server
    build:
      context: config-server
    restart: on-failure
  gateway:
    image: gateway
    container_name: gateway
    build:
      context: gateway
    depends_on:
      - config-server
    restart: on-failure
  bonus-service:
    image: bonus-service
    container_name: bonus-service
    build:
      context: bonus-service
    depends_on:
      - config-server
    restart: on-failure
  flight-service:
    image: flight-service
    container_name: flight-service
    build:
      context: flight-service
    depends_on:
      - config-server
    restart: on-failure
  ticket-service:
    image: ticket-service
    container_name: ticket-service
    build:
      context: ticket-service
    depends_on:
      - config-server
    restart: on-failure
  user-service:
    image: user-service
    container_name: user-service
    build:
      context: user-service
    depends_on:
      - config-server
    restart: on-failure