#spring:
#  r2dbc:
#    url: r2dbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
#    password: ${DATABASE_PASSWORD}
#    username: ${DATABASE_USER}
#    properties:
#      sslMode: REQUIRE

#feign:
#  client:
#    config:
#      default:
#        readTimeout: 15000
#        connectTimeout: 1500
#  service:
#    flightService:
#      base:
#        url: ${FLIGHT_SERVICE_HOST:localhost:8080/api/v1}
#      name: FlightService
